# For configuration options and examples, please see:
# https://github.com/benphelps/homepage/wiki/Services

- My First Group:
    - My First Service:
        href: http://localhost/
        description: Homepage is awesome
        # widget:
        #   type: npm # npm for NGINX Proxy Manager
        #   url: http://localhost # no slash at the end
        #   username: email@example.com # your email
        #   password: secretpassword # your password

- My Second Group:
    - My Second Service:
        href: http://localhost/
        description: Homepage is the best

- My Third Group:
    - My Third Service:
        href: http://localhost/
        description: Homepage is 😎
