# For configuration options and examples, please see:
# https://github.com/benphelps/homepage/wiki/Services

- My First Group:
    - My First Service:
        href: http://localhosdt/
        description: Homepage is awesome

- My Second Group:
    - My Second Service:
        href: http://localhosdt/
        description: Homepage is the best

- My Third Group:
    - My Third Service:
        href: http://localhosdt/
        description: Homepage is 😎
