# For configuration options and examples, please see:
# https://github.com/benphelps/homepage/wiki/Services

- My First Group:
    - My First Service:
        href: http://localhost/
        description: Homepage is awesome
        widget:
          type: npm # npm for NGINX Proxy Manager
          url: http://localhost:81 # no slash at the end
          username: aidenpwnz@proton.me # your email
          password: AidenProxy1994! # your password

- My Second Group:
    - My Second Service:
        href: http://localhost/
        description: Homepage is the best

- My Third Group:
    - My Third Service:
        href: http://localhost/
        description: Homepage is 😎
