name: Bug report
description: Create a report to help us improve
title: "[Bug] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Have a question? 👉 [Start a new discussion](https://github.com/benphelps/homepage/discussions/new) or [ask in chat](https://discord.gg/SaPGSzrEZC).

        Before opening an issue, please double check:

        - [The troubleshooting guide](https://gethomepage.dev/en/more/troubleshooting/).
        - [The homepage documentation](https://gethomepage.dev/)
        - [Existing issues](https://github.com/benphelps/homepage/search?q=&type=issues) and [discussions](https://github.com/benphelps/homepage/search?q=&type=discussions).
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is. If applicable, add screenshots to help explain your problem.
      placeholder: |
        Currently homepage does not work when...

        [Screenshot if applicable]
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. See error
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: homepage version
      placeholder: e.g. v0.4.18 (4ea2798)
    validations:
      required: true
  - type: dropdown
    id: install-method
    attributes:
      label: Installation method
      options:
        - Docker
        - Unraid
        - Source
        - Other (please describe above)
    validations:
      required: true
  - type: textarea
    id: config
    attributes:
      label: Configuration
      description: Please provide any relevant service, widget or otherwise related configuration here
      render: yaml
  - type: textarea
    id: container-logs
    attributes:
      label: Container Logs
      description: Please review and provide any logs from the container, if relevant
  - type: textarea
    id: browser-logs
    attributes:
      label: Browser Logs
      description: Please review and provide any relevant logs from the browser, if relevant
  - type: textarea
    id: other
    attributes:
      label: Other
      description: Any other relevant details. E.g. service version or API version, docker version, etc.
